Created First Section of My Portfolio
Kwaku28/Portfolio pull request #1
Opened 2022-12-01 19:25 UTC by Kwaku28

Created an HTML file that includes:
1. An introduction
2. A brief description of my skill
Added styling to content
A README file that describes the project

2022-12-01 19:58 UTC, amejid reviewed
Hi @Kwaku28 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that lacks some headers of the README template. Kindly use this [template](https://github.com/microverseinc/readme-template) provided by Microverse. The only section you can omit is the `FAQ` section.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-02 09:37 UTC, RiyaBulia12 requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi  @Kwaku28 👋, 

Good job on completing so many requirement checklists in one go! 🎉 🎉 🎉  There are some issues that you still need to work on to go to the next project but you are almost there! 😊 

## Highlight 🎉
- No linter errors :heavy_check_mark:
- Correct GitHub flow :heavy_check_mark:
- New readme file ✔️ 

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._ 🙂 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 09:37 UTC, RiyaBulia12 commented on style.css
> +  margin: 1px 0;
- [ ] Your `<span>` tag which you are using for displaying the menu seems to be very close to one another and looks different from what we have in Figma template. I suggest that you increase the margin to `3px` instead of 1px then it will fix your menu UI. 

Figma Design 👇🏽 
<img width="545" alt="Screenshot 2022-12-02 at 2 14 22 PM" src="https://user-images.githubusercontent.com/24832846/205257263-7b9a34dd-1418-4508-8aa4-ee6630de6af9.png">

Your design 👇🏽 
<img width="373" alt="Screenshot 2022-12-02 at 2 39 10 PM" src="https://user-images.githubusercontent.com/24832846/205257257-3f987c52-1504-4653-b93b-79b24e5696fa.png">

2022-12-02 09:37 UTC, RiyaBulia12 commented on style.css
> +  right: 16.67%;
- [ ] The right spacing for the vector seems a little higher. I think this should be around `right: 7%`to make it look like the  Figma template. Please change this to the correct % to make the UI consistent 🙂  

Your design 👇🏽 
<img width="373" alt="Screenshot 2022-12-02 at 2 50 31 PM" src="https://user-images.githubusercontent.com/24832846/205259383-a379fd6f-aaac-4a77-bde6-1465017c4183.png">
Figma design 👇🏽 
<img width="400" alt="Screenshot 2022-12-02 at 2 51 47 PM" src="https://user-images.githubusercontent.com/24832846/205259721-669d4d21-b70a-4438-b217-2fce4edc4f2c.png">

2022-12-02 09:37 UTC, RiyaBulia12 commented on index.html
> +        <section>
- [x] Kindly make sure that the section has the background image as displayed in the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471&t=Xl4BjuS9X3BknDzr-0) and let's stick to the chosen template. 

| Figma Design | Your Design |
|------------------- | ------------------- |
| ![Figma_1](https://user-images.githubusercontent.com/24832846/205259995-5b289db7-2572-4453-9630-5fa6566e5077.png) | ![Screenshot from 2022-06-29 16-07-51](https://user-images.githubusercontent.com/24832846/205260115-1127c02c-ce9e-48f5-8a32-972076c57c5b.png) |

2022-12-02 09:37 UTC, RiyaBulia12 commented on index.html
> +        </section>
- [ ] Kindly make sure the container of the header section is wrapped inside a `<header>` instead of the `<main>` tag as required for the project and for HTML good semantics. i.e replace `<main> ... </main>` with `<header> ... </header>`. Moreover, kindly remove extra <header> tag on line 14
* **Here is an example of good HTML code that  you can follow:**
```
<header>
   code for the header...
</header>

<main>
   <section>
      code for the 1st section...
   </section>
     
   <section>
      code for the 2nd section...
   </section>
   ....
</main>

<footer>
   Code for the footer...
<footer>
```
- [ ] Kindly make sure once you fixed the above issue, it doesn't affect the styling and if it does, please fix the styling as well to make your design stick to the Figma template. 🙂

2022-12-02 18:00 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @Kwaku28     👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job implementing the requirements! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 
:heavy_check_mark: No Linter Errors :+1: 
:heavy_check_mark: Professional PR :+1: 
:heavy_check_mark: Professional Readme :+1:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
**NA**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 20:37 UTC, frank1738 approved these changes
Hi @Kwaku28 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/U5g8W6hUo0Aixn4vxA/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Good PR Description👍 

## Optional suggestions


N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 22:58 UTC, merged