Project about section added
Kwaku28/Portfolio pull request #2
Opened 2022-12-06 10:25 UTC by Kwaku28

Added project section
Added about section
Included a form
Style update to the various section

2022-12-06 11:36 UTC, Abenezer-Tilahun requested changes
Hi @Kwaku28  , 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ No Linters error
✔️ You used correct GitHub Flow.
✔️ Professional README
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

_Check the comments below the review._
## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                </div>
- [ ] Kindly I recommend to you use a `ul,` each of them in a `li` for list of project technologies (e.g., "JavasScript", "HTML" and "CSS") ,This way will be semantically correct and the screen readers and other technologies will thank you.

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                        </div>
- [ ] Kindly I recommend to you use a `ul,` each of them in a `li` for list of project technologies (e.g., "JavasScript", "HTML" and "CSS") ,This way will be semantically correct and the screen readers and other technologies will thank you.

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                            </div>
- [ ] Kindly I recommend to you use a `ul,` each of them in a `li` for list of project technologies (e.g., "JavasScript", "HTML" and "CSS") ,This way will be semantically correct and the screen readers and other technologies will thank you.

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                            </div>
- [ ] Kindly I recommend to you use a `ul,` each of them in a `li` for list of project technologies (e.g., "JavasScript", "HTML" and "CSS") ,This way will be semantically correct and the screen readers and other technologies will thank you.

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                            </div>
- [ ] Kindly I recommend to you use a `ul,` each of them in a `li` for list of project technologies (e.g., "JavasScript", "HTML" and "CSS") ,This way will be semantically correct and the screen readers and other technologies will thank you.

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                            </div>
- [ ] Kindly I recommend to you use a `ul,` each of them in a `li` for list of project technologies (e.g., "JavasScript", "HTML" and "CSS") ,This way will be semantically correct and the screen readers and other technologies will thank you.

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                            </div>
- [ ] Kindly I recommend to you use a `ul,` each of them in a `li` for list of project technologies (e.g., "JavasScript", "HTML" and "CSS") ,This way will be semantically correct and the screen readers and other technologies will thank you.

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                <input type="button" value="See Project" id="press">
- [ ] Kindly I recommend to you use a a link `a` or `button` tag for the button (e.g., "See project"),and follow the button styling: Active, Hover and Pressed (see design).

- [ ] As stated the project requirement you required to Implement the button interactions (enable, hover, etc.) as see in design, Kindly implement it.

 
![Capture](https://user-images.githubusercontent.com/93598189/205900772-bdcb2e4c-6c30-4c88-bc34-f38fc0651152.PNG)

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                        <input type="button" value="See Project" id="press">
- [ ] Kindly I recommend to you use a a link `a` or `button` tag for the button (e.g., "See project"),and follow the button styling: Active, Hover and Pressed (see design).

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                            <input type="button" value="See Project" id="press">
- [ ] Kindly I recommend to you use a a link `a` or `button` tag for the button (e.g., "See project"),and follow the button styling: Active, Hover and Pressed (see design).

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                            <input type="button" value="See Project" id="press">
- [ ] Kindly I recommend to you use a a link `a` or `button` tag for the button (e.g., "See project"),and follow the button styling: Active, Hover and Pressed (see design).

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                            <input type="button" value="See Project" id="press">
- [ ] Kindly I recommend to you use a a link `a` or `button` tag for the button (e.g., "See project"),and follow the button styling: Active, Hover and Pressed (see design).

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +                            <input type="button" value="See Project" id="press">
- [ ] Kindly I recommend to you use a a link `a` or `button` tag for the button (e.g., "See project"),and follow the button styling: Active, Hover and Pressed (see design).

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +            <input type="button" value="Get My Resume" id="press">
- [ ] Kindly I recommend to you use a a link `a` or `button` tag for the button (e.g., "Get My Resume"),and follow the button styling: Active, Hover and Pressed (see design).

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
>      </footer>
- [ ] For this milestone  you will build the middle section of the mobile website which is "Work" and "About me" section so Kindly remove the "contact me" section which you will build for next milestone.

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on index.html
> +        </section>
- [ ] As stated the project requirement You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). So Kindly makes sure that the "About me" section has the proper background image (decorations are always back-grounded images, not `img` tags)

Your "About me" section Look likes this : 

![Capture](https://user-images.githubusercontent.com/93598189/205898405-5ee256ed-5588-4a22-922d-66680337bb73.PNG)

The Figma design Look likes this : 

![Capture](https://user-images.githubusercontent.com/93598189/205898621-937c641c-ed8a-4c08-83ec-75bbbcdf8b71.PNG)

2022-12-06 11:36 UTC, Abenezer-Tilahun commented on style.css
> +}
- [ ] As stated the project requirement In order to lay out the elements in "Works" section you should use CSS Grid and Flex-box combined (it is mandatory that you use both). **Use CSS Grid in the main container** that contains all of the cards and **use Flex-box to lay out an individual card.** So Kindly fix it.

2022-12-09 14:29 UTC, Yerimah requested changes
# STATUS: REQUIRED CHANGES 🔴 

Hi @Kwaku28 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![So Close Snl GIF by Saturday Night Live](https://user-images.githubusercontent.com/71140133/206724409-e9163573-be98-4d7f-9b70-25c79d4a779b.gif)

 ## Highlights
- No linter errors ✅ 
- Descriptive PR ✅ 
- GitHub flow used ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 14:29 UTC, Yerimah commented on index.html
>                  <a href="#"><ion-icon name="logo-twitter"></ion-icon></a>
- [ ] Great job implementing the Figma design. However, it is very important that you stick to the design as much as possible. In the `header` section of your design, you didn't include the background image. I would kindly suggest you do this in order to make your design as close to the design template as much as possible.

> Your design
![NoIMG](https://user-images.githubusercontent.com/71140133/206720961-9f9b48a3-2b12-4cc4-b7a6-50fa34bd5a8a.PNG)

> Figma Design Template
![bckgroundimg](https://user-images.githubusercontent.com/71140133/206721042-c80d4407-cbcc-4d54-bb3b-4a872234368c.PNG)

- [ ] Secondly, I would suggest you use the same social media icons in the Figma design in your own design. 😁

2022-12-09 14:29 UTC, Yerimah commented on index.html
> +
- [ ] Kindly include the background image in your `about` section as shown on the Figma design. The section has the proper background image (decorations are always backgrounded images, not `img` tags). These background images can be exported from Figma and added to your design.

> Your Design
![NoAboutIMG](https://user-images.githubusercontent.com/71140133/206722294-d1e17a20-e76e-423d-8da1-e11e1aae7f72.PNG)

> Figma Design
![aboutImg](https://user-images.githubusercontent.com/71140133/206722355-d9a7960b-e638-4f20-a43a-51f06609eea9.PNG)

- [ ] Replace the `See project` button with `Get my Resume` in the about section.

2022-12-09 14:29 UTC, Yerimah commented on index.html
> +                    <li>Codepen</li>
- [ ] I would kindly suggest that you properly align to the center of the page the technology categories to look like the design template.

> Your Design
 
![NoAligned](https://user-images.githubusercontent.com/71140133/206723793-2b2f6d60-2388-4a5d-8df5-cdbdadce3812.PNG)

> Figma Design
![Alignedfeat](https://user-images.githubusercontent.com/71140133/206723846-a276e32c-610f-496b-a3ac-b85476e956df.PNG)

2022-12-09 18:30 UTC, Lizdev-05 requested changes
Hi @Kwaku28, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
<img src="https://media2.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

 ## Highlights

- No linter errors ✅
- Descriptive PR ✅
- GitHub flow used ✅

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 18:30 UTC, Lizdev-05 commented on index.html
> +
Great job on the implementation of the corrections made by the previous reviewers 👍. As requested by the previous reviewers, kindly change this part to 'Get my resume' as we have it in the Figma design so that we can meet up with the requirement.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/73854999/206768664-601cdee1-e10b-4fa5-8263-1561224ab283.png">

2022-12-09 19:12 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Kwaku28 

Your project is complete! Great job for making all the changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- design well followed
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 22:34 UTC, merged